# Generated by Django 3.1.5 on 2021-01-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=120)),
                ('nick_name', models.CharField(max_length=300)),
                ('description_name', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(max_length=3)),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
