# Generated by Django 3.1.5 on 2021-02-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_country_country_code2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_code',
            new_name='country_code3',
        ),
    ]
