# Generated by Django 3.1.5 on 2021-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20210209_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
