# Generated by Django 3.1.5 on 2021-02-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20210205_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='nick_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
