# Generated by Django 3.1.5 on 2021-02-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_auto_20210209_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='description_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='nick_name',
        ),
    ]
