# Generated by Django 3.1.6 on 2021-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0015_auto_20210211_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_flag',
            field=models.FileField(blank=True, upload_to='country/country-flag-svg'),
        ),
    ]
