# Generated by Django 3.1.7 on 2021-02-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameplay', '0016_auto_20210212_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectGameplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_game', models.CharField(max_length=120)),
                ('level_of_game', models.CharField(max_length=120)),
                ('game_mode', models.CharField(max_length=120)),
                ('game_mode_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_game', models.CharField(max_length=120)),
                ('level_of_game', models.CharField(max_length=120)),
                ('game_mode', models.CharField(max_length=120)),
                ('game_mode_description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
