# Generated by Django 3.1.7 on 2021-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0019_auto_20210222_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectgameplay',
            name='game_mode',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='selectgameplay',
            name='level_of_game',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='selectgameplay',
            name='type_of_game',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
