# Generated by Django 3.1.7 on 2021-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0020_auto_20210222_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectgameplay',
            name='game_mode',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='selectgameplay',
            name='level_of_game',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='selectgameplay',
            name='type_of_game',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
