# Generated by Django 3.1.7 on 2021-02-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0022_auto_20210224_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='user',
        ),
    ]
