# Generated by Django 3.1.7 on 2021-03-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0024_userselection_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userselection',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='userselection',
            old_name='type_of_game',
            new_name='game_type',
        ),
    ]
