# Generated by Django 3.1.7 on 2021-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0025_auto_20210303_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselection',
            old_name='level_of_game',
            new_name='game_level',
        ),
        migrations.AddField(
            model_name='userselection',
            name='game_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userselection',
            name='game_css',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userselection',
            name='game_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userselection',
            name='game_template',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
