# Generated by Django 3.1.7 on 2021-03-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0027_auto_20210303_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-id']},
        ),
    ]
